version: "3.5"

services:
  db:
    container_name: node_mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    container_name: node_mongo_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: node_mongo
    user: "node"
    environment:
      NODE_ENV: development
      DB_USER: root
      DB_PASSWORD: mongo
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: node_mongo
    volumes:
      - ./:/app
    command: "npm run dev"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
